Ali/umi fifo flex merge
zeroasiccorp/umi pull request #116
Opened 2024-02-13 16:45 UTC by azaidy

Add merge capability to umi fifo flex.
The FIFO will automatically merge transactions when ODW > IDW.

2024-02-13 21:07 UTC, volkamir commented on umi/testbench/testbench_fifo_flex.sv
> +   ///////////////////////////////////////////
It is not good to do this in the testbench, The dut should be responsible for not providing ready until the reset is one so it needs to be fixed in the fifo itself.

2024-02-13 21:07 UTC, volkamir commented on umi/rtl/umi_fifo_flex.v
> +        assign len_mergeable = (latch_bytes + latch_in_bytes) <= (ODW >> 3);
Is this limiting the merge in case it crosses the boundary of ODW? 
Sounds like a reasonable limitation, just to make sure.

2024-02-13 23:10 UTC, azaidy commented on umi/testbench/testbench_fifo_flex.sv
> +   ///////////////////////////////////////////
Fixed.

2024-02-13 23:15 UTC, azaidy commented on umi/rtl/umi_fifo_flex.v
> +        assign len_mergeable = (latch_bytes + latch_in_bytes) <= (ODW >> 3);
Fixed. Added this limitation to the header.

2024-02-16 19:05 UTC, volkamir approved these changes
Looks good.

2024-02-20 23:54 UTC, volkamir requested changes

2024-02-20 23:54 UTC, volkamir commented on utils/rtl/umi2tl_np.v
> +    /* verilator lint_off WIDTHTRUNC */
Please do not waive the warnings but fix it. The fix should be by defining the size of the '1' you shift level.

2024-02-20 23:54 UTC, volkamir commented on utils/rtl/umi_packet_merge_greedy.v
> +    /* verilator lint_off WIDTHTRUNC */
Same comment.

2024-02-21 03:11 UTC, azaidy commented on utils/rtl/umi2tl_np.v
> +    /* verilator lint_off WIDTHTRUNC */
The issue is now fixed. The error was stemming from the multiplication. Making the output signal the size of the biggest input operand (8 bits) fixes it.

2024-02-21 03:11 UTC, azaidy commented on utils/rtl/umi_packet_merge_greedy.v
> +    /* verilator lint_off WIDTHTRUNC */
The issue is now fixed. The error was stemming from the multiplication. Making the output signal the size of the biggest operand (8 bits) fixes it.

2024-02-21 03:23 UTC, volkamir approved these changes
Approving with the waiver for now. Will revisit.

2024-02-21 03:23 UTC, merged